name: CI

on:
  push:
  pull_request:

jobs:
  nodejs:
    name: Node.js
    runs-on: ubuntu-latest
    concurrency: ci-nodejs-${{ github.ref }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install Packages
        run: pnpm install --frozen-lockfile

        # Tests
      - name: Build Tests
        working-directory: ./tests
        run: pnpm build

      - name: Validate Definitions
        working-directory: ./tests
        run: pnpm validateDefinitions

      - name: Validate SVGs
        working-directory: ./tests
        run: pnpm validateSvgs
        continue-on-error: true

        # Client
      - name: Build Client
        working-directory: ./client
        run: pnpm build
        continue-on-error: true

        # Server
      - name: Build Server
        working-directory: ./server
        run: pnpm build
        continue-on-error: true

        # Lint
      - name: Lint
        run: pnpm lint:ci
